### ISSUE TITLE
ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by C0b3lt** [pikaflufftuft/pikaft-e621-posts-downloader#8]
When trying to run the python script, I get this error
![Screenshot 2024-05-23 222953](https://github.com/pikaflufftuft/pikaft-e621-posts-downloader/assets/121405316/e2813a12-8370-4307-afe5-26808c54ff38)

**Comment by pikaflufftuft** [comment]
Have you tried running the second part of the requirements specified in Readme?
You need to install the required modules.
`pip install -r requirements.txt`
